### ISSUE TITLE
osslsigncode Issues

### ISSUE THREAD

**Issue by ssnkhan** [Sentinel-One/VTgrepGHIDRA#1]
Hello,

Are there any special considerations for installing `osslsigncode`? I have attempted installation using `apt-get` and compiling from source, but VTGhidra still does not acknowledge the installation, dispite being able to use `osslsigncode` via the CLI. 

I am running the latest version of Ghidra (installed via the deb file) on ParrotOS.

**Comment by kasif-dekel** [comment]
Thanks! Fixed it. Re-open or create a new issue if the problem persists.

**Comment by ssnkhan** [comment]
Thank you -- `osslsigncode` is now recognised, but all binaries return a "Something went wrong processing this file" error. Am I meant to be selecting specific assembly code when using the key search feature? I was expecting `osslsigncode` to extract the key from the binary as a whole, and search based on that. Many thanks!

**Comment by kasif-dekel** [comment]
Could you please provide the binary you loaded to GHIDRA? Thanks
Also, please provide the output of  `osslsigncode verify -in <file> -CAfile /dev/null` on your machine

**Comment by ssnkhan** [comment]
I am testing on a known signed MS binary, `csrss.exe`, available at https://www.virustotal.com/gui/file/6f1c9b4c187669bc0371260d121caf48d65f829a9104c483befbd8fc0bed24f5/details

```
osslsigncode verify -in ~/Desktop/6f1c9b4c187669bc0371260d121caf48d65f829a9104c483befbd8fc0bed24f5 -CAfile /dev/null 
Unknown option: -CAfile
```

**Comment by kasif-dekel** [comment]
It seems like you're using an outdated version of `osslsigncode` please compile from the sources as stated project README.

**Comment by ssnkhan** [comment]
Forcing a fresh install did it -- many thanks for your patience, now looking forward to the webinar next week!
